'use client';
import React, { useEffect } from 'react';
import { FaInstagram } from 'react-icons/fa'; // ✅ React Icon import

const CounterSection = () => {
  useEffect(() => {
    const odometerElements = document.querySelectorAll('.odometer');

    odometerElements.forEach((element) => {
      element.innerHTML = '0';

      const countStr = element.getAttribute('data-count');
      if (countStr) {
        const targetCount = parseInt(countStr, 10);
        let currentCount = 0;
        const step = Math.ceil(targetCount / 100); // smooth and quick
        const interval = setInterval(() => {
          currentCount += step;
          if (currentCount >= targetCount) {
            currentCount = targetCount;
            clearInterval(interval);
          }
          element.innerHTML = currentCount.toString();
        }, 10);
      }
    });
  }, []);

  const blocks = [
    {
      count: 8000,
      text: 'More than 8,000 customers have experimented with Kafkai',
    },
    {
      count: 500000,
      text: 'More than 500,000 articles generated by Kafkai',
    },
    {
      count: 200000,
      text: 'More than 200,000 hours saved using Kafkai',
    },
  ];

  return (
    <section className="choose-three style-two">
      <div className="auto-container">
        <div className="inner-container">
          <div className="row clearfix">
            {blocks.map((block, index) => (
              <div
                key={index}
                className="counter-block_one col-lg-4 col-md-6 col-sm-12"
              >
                <div
                  className="counter-block_one-inner wow fadeInLeft"
                  data-wow-delay={`${index * 150}ms`}
                  data-wow-duration="1500ms"
                >
                  <div className="counter-block_one-icon">
                    <FaInstagram size={50} /> {/* 🔥 Increased icon size to 50 */}
                  </div>
                  <div className="counter-block_one-count">
                    <span className="odometer" data-count={block.count}></span>
                    <i>+</i>
                  </div>
                  <div className="counter-block_one-text">{block.text}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default CounterSection;
