'use client';
import { useState } from 'react';
import { FaPlus, FaMinus } from 'react-icons/fa';

type FAQItem = {
  question: string;
  answer: string;
};

const faqData: FAQItem[] = [
  {
    question: 'How does your AI copywriting tool work?',
    answer:
      'Our AI copywriting tool uses sophisticated algorithms to understand context, tone, and language nuances. Users input specific details or prompts, and the AI generates high-quality content based on that input, refining.',
  },
  {
    question: 'What is AI copywriting?',
    answer:
      'AI copywriting is the use of artificial intelligence to automatically generate written content like ads, blogs, emails, etc.',
  },
  {
    question: 'Can I trust the content generated by AI?',
    answer:
      'Yes, but it’s always good to review and customize it to your tone and needs.',
  },
  {
    question: 'What types of content can your AI generate?',
    answer:
      'Blogs, product descriptions, ad copy, emails, website content, and more.',
  },
  {
    question: 'What languages does your AI support?',
    answer:
      'Our tool supports over 20 major languages including English, Spanish, French, and more.',
  },
];

const FAQSection = () => {
  const [activeIndex, setActiveIndex] = useState<number | null>(null);

  const toggleAccordion = (index: number) => {
    setActiveIndex(activeIndex === index ? null : index);
  };

  return (
    <section className="faq-one style-four">
      <div className="auto-container">
        <div className="row clearfix">
          {/* Tab Column */}
          <div className="faq-one_title-column col-lg-5 col-md-12 col-sm-12">
            <div className="faq-one_title-outer">
              <div className="sec-title style-four">
                <div className="sec-title_title">faq</div>
                <h2 className="sec-title_heading">
                  Frequently asked <span>questions</span>
                </h2>
                <div className="sec-title_text">
                  Lorem ipsum dolor sit amet consectetur adipiscing vitae mattis
                  tellus. Nullam quis mattis ligula consectetur.
                </div>
              </div>
              <div className="faq-one_button">
                <a href="contact.html" className="template-btn btn-style-one">
                  <span className="btn-wrap">
                    <span className="text-one">Contact now</span>
                    <span className="text-two">Contact now</span>
                  </span>
                </a>
              </div>
            </div>
          </div>

          {/* Accordion Column */}
          <div className="faq-one_accordian-column col-lg-7 col-md-12 col-sm-12">
            <div className="faq-one_accordian-outer">
              <ul className="accordion-box_two">
                {faqData.map((item, index) => (
                  <li className="accordion block" key={index}>
                    <div
                      className={`acc-btn ${activeIndex === index ? 'active' : ''}`}
                      onClick={() => toggleAccordion(index)}
                      style={{ cursor: 'pointer' }}
                    >
                      <div className="icon-outer">
                        <span className="icon">
                          {activeIndex === index ? <FaMinus /> : <FaPlus />}
                        </span>
                      </div>
                      {item.question}
                    </div>
                    <div
                      className="acc-content"
                      style={{
                        display: activeIndex === index ? 'block' : 'none',
                      }}
                    >
                      <div className="content">
                        <div className="text">{item.answer}</div>
                      </div>
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default FAQSection;
